/** Package export surface — grows as Components ship. See src/package.manifest.ts for the full manifest. */
export { Badge, type BadgeEmphasis, type BadgeLayoutClassName, type BadgeProps, type BadgeSize, type BadgeVariant, badgeEmphases, badgeVariants } from "./components/atoms/Badge/Badge";
export {
  Button,
  buttonLayouts,
  buttonRoles,
  type ButtonLayout,
  type ButtonLayoutClassName,
  type ButtonProps,
  type ButtonRole,
  type ButtonSize,
  type ButtonStatus,
  defaultStatusLabels,
  getNextButtonStatus,
} from "./components/atoms/Button/Button";
export {
  IconButton,
  type IconButtonLayoutClassName,
  type IconButtonProps,
  type IconButtonSize,
} from "./components/atoms/IconButton/IconButton";
export {
  Input,
  inputMessagePositions,
  inputSizes,
  inputStatuses,
  type InputLayoutClassName,
  type InputMessagePosition,
  type InputProps,
  type InputSize,
  type InputStatus,
} from "./components/atoms/Input/Input";
export {
  Status,
  statusRingSizePx,
  statusTones,
  statusVariants,
  type StatusDotVariantProps,
  type StatusLayoutClassName,
  type StatusProps,
  type StatusRingVariantProps,
  type StatusTone,
  type StatusVariant,
} from "./components/atoms/Status/Status";
export {
  Chip,
  ChipFilterGroup,
  chipSizes,
  type ChipFilterGroupProps,
  type ChipLayoutClassName,
  type ChipProps,
  type ChipSelectionMode,
  type ChipSize,
} from "./components/molecules/Chip/Chip";
export {
  Accordion,
  accordionVariants,
  type AccordionItemProps,
  type AccordionLayoutClassName,
  type AccordionProps,
  type AccordionVariant,
} from "./components/molecules/Accordion/Accordion";
export {
  Card,
  cardAddressClasses,
  cardBodyTextClasses,
  cardBodyWellClasses,
  cardLayoutBodyOccupantInsetXClasses,
  cardLayoutBodyOccupantDotGridWellClasses,
  cardLayoutBodyOccupantWellClasses,
  cardPaddings,
  cardShapes,
  cardSubtitleClasses,
  cardTitleClasses,
  cardVariants,
  type CardHeaderProps,
  type CardLayoutClassName,
  type CardPadding,
  type CardProps,
  type CardSectionProps,
  type CardShape,
  type CardVariant,
} from "./components/molecules/Card/Card";
export {
  Search,
  searchSizes,
  type SearchLayoutClassName,
  type SearchProps,
  type SearchSize,
} from "./components/molecules/Search/Search";
export {
  TaskRows,
  taskRowStatuses,
  taskRowsDetailLayouts,
  taskRowsDetailVariants,
  taskRowsVariants,
  type TaskRowStatus,
  type TaskRowsDetailLayout,
  type TaskRowsDetailProps,
  type TaskRowsDetailVariant,
  type TaskRowsItemProps,
  type TaskRowsLabels,
  type TaskRowsLayoutClassName,
  type TaskRowsProps,
  type TaskRowsVariant,
} from "./components/molecules/TaskRows/TaskRows";
export {
  Chart,
  chartFormatPercent,
  chartKpiHeroRowClasses,
  chartKpiHeroValueClasses,
  chartKpiTrendLabelClasses,
  chartKpiTrendRowClasses,
  chartKpiTrendValueClasses,
  chartMaxTicksForWidth,
  chartSegmentBarWidth,
  chartSegmentFillVariants,
  chartSegmentPresets,
  chartSegmentTickSpec,
  resolveCapacityBarLayout,
  resolveSegmentBarConfig,
  type ChartLayoutClassName,
  type ChartSegmentFillVariant,
  type ChartSegmentPreset,
  type ChartSegmentedBarProps,
  type ChartTone,
} from "./components/organisms/Chart/Chart";
export {
  chartBucketPeriodData,
  chartCategoricalCount,
  chartCategoricalPalette,
  chartNormalizePeriodData,
  chartSeriesColor,
  resolvePeriodSegmentPreset,
  resolvePeriodSegments,
  type ChartBucketPeriodOptions,
  type ChartPeriod,
  type ChartPeriodAggregate,
  type ChartPeriodBucket,
  type ChartPeriodKind,
  type ChartPeriodPoint,
  type ChartSegmentTickSpec,
} from "./lib/chartTheme";
export {
  backgroundPatternDiagonalLinesClasses,
  backgroundPatternDotGridClasses,
  backgroundPatterns,
  type BackgroundPatternId,
} from "./lib/backgroundPatterns";
export { cn } from "./lib/cn";
export { GridOverlay, type GridOverlayProps } from "./lib/GridOverlay";
export {
  GRID_ON_CLASS,
  gridOverlayKeyShouldToggle,
  isEditableGridOverlayTarget,
  readGridColumnCount,
  setDocumentGridOn,
} from "./lib/gridOverlayUtils";
export {
  focusRingTransitionClasses,
  motionTransition,
  motionTransitionProp,
  pressScaleClass,
  type MotionDuration,
  type MotionEase,
} from "./lib/motion";
